{
    "totalSize": 1,
    "done": true,
    "records": [
        {
            "attributes": {
                "type": "Case",
                "url": "/services/data/v54.0/sobjects/Case/5009t00000634rfAAA"
            },
            "Id": "5009t00000634rfAAA",
            "Data_Quality_check_completed__c": false,
            "Is_this_a_Variant_of_Concern_VOC__c": null,
            "Variant_of_Concern_Screening_Result__c": null,
            "If_yes_which_VOC__c": null,
            "Sensitive__c": null,
            "Sero_Group_Subtype__c": "COVID-19",
            "Source_Interface__c": null,
            "CaseNumber": "31691026",
            "Account": {
                "attributes": {
                    "type": "Account",
                    "url": "/services/data/v54.0/sobjects/Account/0019t00000AarHlAAJ"
                },
                "FirstName": "Autogdsx",
                "LastName": "Iomd"
            },
            "Clinical_Care_Status__c": null,
            "Case_Found_By__c": "Clinical Presentation",
            "Date_of_Test__c": "9/1/2021",
            "Was_aware_of_contact_with_ve_case__c": null,
            "Description": null,
            "Healthcare_Worker__c": null,
            "Confirmation_Date__c": "28/4/2023, 3:14 pm",
            "RecordTypeId": "0122e0000004NYuAAM",
            "Owner": {
                "attributes": {
                    "type": "Name",
                    "url": "/services/data/v54.0/sobjects/Group/00G2P000000OMaYUAW"
                },
                "Name": "Informatics"
            },
            "Case_Classification__c": "Confirmed",
            "Specifyrelationshiptocase__c": null,
            "Organism_Cause__c": "COVID-19",
            "Epi_Classification__c": "Sporadic case",
            "Origin": null
        }
    ]
}
